### ISSUE TITLE
issue with commented styles

### ISSUE THREAD

**Issue by mfouad** [snovakovic/vtpw#3]
The extension comments the <style> section using /* .. */
but if the style sction contains any commented styles it will break the file

![image](https://user-images.githubusercontent.com/977064/82013116-bd569a00-9679-11ea-8719-5481a86765f7.png)

I suggest the style sctions get commented using //

P.S. This is the best invention since hot cakes!

**Comment by snovakovic** [comment]
@mfouad Glad you find the plugin useful :tada: 

I push the fix for the above issue when with v0.1.0 version. 

Will close the issue but let me know if anything when you try it out
